name: dotnet pack
description: Packs the Ghostlogger MSBuild task NuGet package
inputs:
  buildConfiguration:
    default: Release
    description: The dotnet build configuration
    required: false
  versionSuffix:
    default: ''
    description: The optional assembly and NuGet version suffix
    required: false
  sign:
    default: 'false'
    description: Indicates whether the assemblies should be both code signed and signed with a strong name.
    required: false
  azureTenantId:
    default: ''
    description: The Azure tenant ID for service principal used to access the Azure Key Vault and Azure Code Signing Service.
    required: false
  azureClientId:
    default: ''
    description: The client ID for the service principal used to access the Azure Key Vault and Azure Code Signing Service.
    required: false
  azureSubscriptionId:
    default: ''
    description: The Azure subscription ID containing both the Azure Key Vault and Azure Code Signing Service.
    required: false
  strongNameExe:
    default: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/sn.exe'
    description: The path to the sn.exe tool used to sign the assemblies with a strong name. Requires a Windows runner.
    required: false
  azureKeyVaultName:
    default: ''
    description: The name of the Azure Key Vault containing the Ghostlogger strong name key.
    required: false
  azureCodeSigningAccountName:
    default: ''
    description: The name of the Azure Code Signing account containing the Ghostlogger certificate profile.
    required: false
  strongNameKeySecretName:
    default: ''
    description: The name of the secret for the Ghostlogger strong name key.
    required: false
  certificateProfileName:
    default: ''
    description: The name of the certificate profile within the Azure Code Signing Service.
  codeSigningUri:
    default: 'https://wus.codesigning.azure.net/'
    description: The URI of the Azure Code Signing Service.
    required: false
  repositoryUri:
    default: 'https://github.com/wsugarman/ghostlogger'
    description: The URI of the Ghostlogger repository
    required: false

runs:
  using: composite
  steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: 'global.json'
        dotnet-version: '6.x'

    - if: ${{ inputs.sign == 'true' && success() }}
      name: az login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azureClientId }}
        tenant-id: ${{ inputs.azureTenantId }}
        subscription-id: ${{ inputs.azureSubscriptionId }}

    - if: ${{ inputs.sign == 'true' && success() }}
      name: Fetch Strong Name Key Secret
      id: akv
      shell: bash
      run: |
        key=$(az keyvault secret show -n "${{ inputs.strongNameKeySecretName }}" --vault-name "${{ inputs.azureKeyVaultName }}" --query value -o tsv)
        echo "::add-mask::$key"
        echo "snk=$key" >> "$GITHUB_OUTPUT"

    - if: ${{ inputs.sign == 'true' && success() }}
      name: Create .snk File
      shell: bash
      run: |
        mkdir -p "${{ runner.temp }}/snk/"
        echo $STRONG_NAME_KEY_BASE64 | base64 --decode > "${{ runner.temp }}/snk/Private.snk"
      env:
        STRONG_NAME_KEY_BASE64: ${{ steps.akv.outputs.snk }}

    - name: Build
      shell: bash
      run: |
        dotnet build "./src/task/Ghostlogger/Ghostlogger.csproj" \
          -c "${{ inputs.buildConfiguration }}" \
          "-p:ContinuousIntegrationBuild=true;VersionSuffix=${{ inputs.versionSuffix }}" \
          -warnaserror

    - if: ${{ inputs.sign == 'true' && success() }}
      name: Sign with Enhanced Strong Name
      shell: bash
      run: |
        "${{ inputs.strongNameExe }}" -Ra "./src/task/Ghostlogger/bin/${{ inputs.buildConfiguration }}/netstandard2.0/Ghostlogger.dll" "${{ runner.temp }}/snk/Private.snk"

    - if: ${{ inputs.sign == 'true' && success() }}
      name: Extract Assembly Attributes
      id: assembly
      shell: pwsh
      run: |
        $assembly = [System.Reflection.Assembly]::LoadFile('${{ github.workspace }}/src/task/Ghostlogger/bin/${{ inputs.buildConfiguration }}/netstandard2.0/Ghostlogger.dll')
        $description = $assembly.GetCustomAttributes([System.Reflection.AssemblyDescriptionAttribute], $false).Description
        "description=$description" >> $env:GITHUB_OUTPUT

    - if: ${{ inputs.sign == 'true' && success() }}
      name: Code Sign Assembly
      shell: pwsh
      run: |
        Install-Module -Name AzureCodeSigning -RequiredVersion 0.2.21 -Force -Repository PSGallery
        Invoke-AzureCodeSigning `
          -Endpoint '${{ inputs.codeSigningUri }}' `
          -CodeSigningAccountName '${{ inputs.azureCodeSigningAccountName }}' `
          -CertificateProfileName '${{ inputs.certificateProfileName }}' `
          -FilesFolder './src/task/Ghostlogger/bin/${{ inputs.buildConfiguration }}/netstandard2.0' `
          -FilesFolderFilter 'dll' `
          -FileDigest 'SHA256' `
          -TimestampRfc3161 'http://timestamp.acs.microsoft.com' `
          -TimestampDigest 'SHA256' `
          -Description '${{ steps.assembly.outputs.description }}' `
          -DescriptionUrl '${{ inputs.repositoryUri }}'

    # TODO: Sign and push package
    - name: Pack
      shell: bash
      run: |
        dotnet pack "./src/task/Ghostlogger/Ghostlogger.csproj" \
          -c "${{ inputs.buildConfiguration }}" \
          "-p:ContinuousIntegrationBuild=true;VersionSuffix=${{ inputs.versionSuffix }}" \
          --no-build \
          -o "${{ runner.temp }}/package"

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: ${{ runner.temp }}/package

    - if: ${{ inputs.sign == 'true' && always() }}
      name: Delete .snk File
      shell: bash
      run: |
        rm -f "${{ runner.temp }}/snk/Private.snk"

    - if: ${{ inputs.sign == 'true' && always() }}
      name: az logout
      shell: bash
      run: |
        az logout
        az cache purge
        az account clear
